// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Mocha$RescriptMocha = require("rescript-mocha/lib/js/src/Mocha.bs.js");
var Assert$RescriptMocha = require("rescript-mocha/lib/js/src/Assert.bs.js");
var MlErrorMetricFunction = require("../src/MlErrorMetricFunction.bs.js");

function approxEq(x, y) {
  return (x - y) * (x - y) < 0.01;
}

Mocha$RescriptMocha.describe("test EuclideanErrorMetric")(undefined, undefined, undefined, (function (param) {
        Mocha$RescriptMocha.it("test 1")(undefined, undefined, undefined, (function (param) {
                var result = MlErrorMetricFunction.ErrorMetricEuclidean.errToFloat(MlErrorMetricFunction.ErrorMetricEuclidean.errMetricDerivative(1.0, 0.5));
                Assert$RescriptMocha.ok(approxEq(result, -0.5));
              }));
      }));

exports.approxEq = approxEq;
/*  Not a pure module */
