// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function solve(x) {
  return 1.0 / (1.0 + Math.exp(- x));
}

function derivative(x) {
  var s = solve(x);
  return s * (1.0 - s);
}

var ActivFuncSigmoid = {
  solve: solve,
  derivative: derivative
};

function solve$1(x) {
  return Math.max(0.0, x);
}

function derivative$1(x) {
  if (x > 0.0) {
    return 1.0;
  } else {
    return 0.0;
  }
}

var ActivFuncReLU = {
  solve: solve$1,
  derivative: derivative$1
};

function solve$2(x) {
  return (Math.exp(x) - Math.exp(- x)) / (Math.exp(x) + Math.exp(- x));
}

function derivative$2(x) {
  var s = solve$2(x);
  return 1.0 - s * s;
}

var ActivFuncTh = {
  solve: solve$2,
  derivative: derivative$2
};

exports.ActivFuncSigmoid = ActivFuncSigmoid;
exports.ActivFuncReLU = ActivFuncReLU;
exports.ActivFuncTh = ActivFuncTh;
/* No side effect */
