// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function errToFloat(errVal) {
  return errVal;
}

function floatToErr(f) {
  return f;
}

function errMetricDerivative(nominal, result) {
  return result - nominal;
}

var ErrorMetricEuclidean = {
  errToFloat: errToFloat,
  floatToErr: floatToErr,
  errMetricDerivative: errMetricDerivative
};

exports.ErrorMetricEuclidean = ErrorMetricEuclidean;
/* No side effect */
